# Verification Configuration
# Single source of truth for verification requirements.

node_version: ">= 18.0.0"

steps:
  - name: "Install dependencies"
    command: "npm ci"
    required: true
    description: "Install Node dependencies from lockfile"

  - name: "Type check"
    command: "npx tsc --noEmit"
    required: true
    description: "TypeScript type checking"

  - name: "Test"
    command: "npm run test:ci"
    required: true
    description: "Run Vitest suite in CI mode"

  - name: "Build"
    command: "npm run build"
    required: true
    description: "Vite production build to dist/"

dev:
  command: "npm run dev"
  port: 5173
  url: "http://localhost:5173"

agent_notes: |
  - Run script/verify for full verification
  - npm run build must produce dist/ with index.html, 404.html, CNAME
  - npm run test:ci runs Vitest with CI-friendly verbose output
